// Generates src/lib/api/generated/codes.ts from the backend code-registry manifest.
//
// The backend is the single source of truth for stable codes ([Code] enums, capability
// discriminators, external-id provider keys, and setting keys). This script fetches the
// dev-only manifest endpoint and emits matching TypeScript constants so the frontend never
// hand-maintains these values. Run as part of `pnpm api:generate` (after orval), against a
// running dev API.

import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUTPUT = resolve(__dirname, "../src/lib/api/generated/codes.ts");

const openApiUrl = process.env.PRISMEDIA_OPENAPI_URL ?? "http://127.0.0.1:8008/openapi/v1.json";
const codesUrl = process.env.PRISMEDIA_CODES_URL ?? new URL("/api/_codegen/codes.json", openApiUrl).toString();

// Backend enum type name -> [exported const name, exported type name].
const ENUM_EXPORTS = [
  ["EntityKind", "ENTITY_KIND", "EntityKindCode"],
  ["ProposalKind", "PROPOSAL_KIND", "ProposalKindCode"],
  ["RelationshipKind", "RELATIONSHIP_CODE", "RelationshipCode"],
  ["EntityFileRole", "ENTITY_FILE_ROLE", "EntityFileRoleCode"],
  ["CreditRole", "CREDIT_ROLE", "CreditRoleCode"],
  ["JobType", "JOB_TYPE", "JobTypeCode"],
  ["JobRunStatus", "JOB_RUN_STATUS", "JobRunStatusCode"],
  ["PlaybackMode", "PLAYBACK_MODE", "PlaybackModeCode"],
  ["MusicPlayerRepeatMode", "MUSIC_PLAYER_REPEAT_MODE", "MusicPlayerRepeatModeCode"],
  ["MusicPlayerMiniSide", "MUSIC_PLAYER_MINI_SIDE", "MusicPlayerMiniSideCode"],
  ["EntitySubtitleSource", "SUBTITLE_SOURCE", "SubtitleSourceCode"],
  ["SubtitleStyle", "SUBTITLE_STYLE", "SubtitleStyleCode"],
  ["IdentifyQueueState", "IDENTIFY_QUEUE_STATE", "IdentifyQueueStateCode"],
  ["IdentifyResultStatus", "IDENTIFY_RESULT_STATUS", "IdentifyResultStatusCode"],
  ["FileSourceKind", "FILE_SOURCE_KIND", "FileSourceKindCode"],
];

const camel = (name) => (name.length === 0 ? name : name[0].toLowerCase() + name.slice(1));
const lit = (value) => JSON.stringify(value);

function constBlock(constName, typeName, entries) {
  const body = entries.map(([key, value]) => `  ${key}: ${lit(value)},`).join("\n");
  return (
    `export const ${constName} = {\n${body}\n} as const;\n\n` +
    `export type ${typeName} = (typeof ${constName})[keyof typeof ${constName}];\n`
  );
}

async function main() {
  const response = await fetch(codesUrl);
  if (!response.ok) {
    throw new Error(`Failed to fetch codes manifest from ${codesUrl}: ${response.status} ${response.statusText}`);
  }
  const manifest = await response.json();

  const sections = [];

  for (const [enumName, constName, typeName] of ENUM_EXPORTS) {
    const members = manifest.enums?.[enumName];
    if (!members) {
      throw new Error(`Manifest is missing enum '${enumName}'. Is the backend up to date?`);
    }
    sections.push(constBlock(constName, typeName, members.map((m) => [camel(m.name), m.code])));
  }

  // Capability discriminators (keyed by the code itself).
  sections.push(
    constBlock(
      "CAPABILITY_KIND",
      "CapabilityKindCode",
      (manifest.capabilityKinds ?? []).map((code) => [camel(code), code]),
    ),
  );

  // Well-known external-id providers.
  sections.push(
    constBlock(
      "EXTERNAL_ID_PROVIDER",
      "ExternalIdProviderCode",
      (manifest.externalIdProviders ?? []).map((c) => [camel(c.name), c.value]),
    ),
  );

  // App setting keys (preserves the camelCase member -> dotted key shape consumers expect).
  sections.push(
    constBlock(
      "SETTING_KEYS",
      "SettingKey",
      (manifest.settingKeys ?? []).map((c) => [camel(c.name), c.value]),
    ),
  );

  // Entity-kind plural display labels, keyed by kind code.
  const labelEntries = (manifest.entityKinds ?? []).map((k) => `  ${lit(k.code)}: ${lit(k.groupLabel)},`).join("\n");
  sections.push(
    `export const ENTITY_KIND_LABELS: Record<EntityKindCode, string> = {\n${labelEntries}\n};\n`,
  );

  const header =
    "// AUTO-GENERATED by scripts/gen-codes.mjs from the backend code-registry manifest.\n" +
    "// Do not edit by hand. Run `pnpm api:generate` (with the dev API running) to refresh.\n" +
    "/* eslint-disable */\n";

  mkdirSync(dirname(OUTPUT), { recursive: true });
  writeFileSync(OUTPUT, `${header}\n${sections.join("\n")}`);
  console.log(`Wrote ${OUTPUT}`);
}

main().catch((error) => {
  console.error(error.message ?? error);
  process.exit(1);
});
