// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Prismedia.Infrastructure.Persistence;

#nullable disable

namespace Prismedia.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PrismediaDbContext))]
    [Migration("20260612021500_AddPendingJobRunDedupeIndex")]
    partial class AddPendingJobRunDedupeIndex
    {
    }
}
