packages:
  - apps/*
  - documentation-site
  - packages/*

onlyBuiltDependencies:
  - esbuild

patchedDependencies:
  '@easyops-cn/docusaurus-search-local@0.55.3': patches/@easyops-cn__docusaurus-search-local@0.55.3.patch
