namespace Prismedia.Domain.Entities;

/// <summary>
/// Closed set of subtitle discovery or generation sources.
/// </summary>
public enum EntitySubtitleSource {
    /// <summary>User supplied subtitle file.</summary>
    [Code("manual")]
    Manual,

    /// <summary>Subtitle stream extracted from source media.</summary>
    [Code("embedded")]
    Embedded,

    /// <summary>Subtitle generated by a local service.</summary>
    [Code("generated")]
    Generated,

    /// <summary>Subtitle imported from a metadata or subtitle provider.</summary>
    [Code("provider")]
    Provider,

    /// <summary>Subtitle uploaded by the user.</summary>
    [Code("upload")]
    Upload,

    /// <summary>Subtitle discovered as a sidecar file alongside the media.</summary>
    [Code("sidecar")]
    Sidecar
}
