export const apiRoutes = {
  health: "/health",
  changelog: "/changelog",
  jobs: "/jobs",
  jobQueueRun: "/jobs/queues/:queueName/run",
  jobCancelAll: "/jobs/cancel-all",
  jobRunCancel: "/jobs/:jobRunId/cancel",
  jobAcknowledgeFailed: "/jobs/acknowledge-failed",
  libraries: "/libraries",
  libraryDetail: "/libraries/:id",
  libraryBrowse: "/libraries/browse",
  librarySettings: "/settings/library",
  galleries: "/galleries",
  galleryDetail: "/galleries/:id",
  galleryStats: "/galleries/stats",
  galleryCover: "/galleries/:id/cover",
  galleryImageUpload: "/galleries/:id/images/upload",
  galleryChapters: "/galleries/:id/chapters",
  galleryChapterDetail: "/galleries/chapters/:id",
  images: "/images",
  imageDetail: "/images/:id",
  imagesBulk: "/images/bulk",
  imageAssets: "/assets/images/:id/*",
  galleryCoverAsset: "/assets/galleries/:id/cover",
  books: "/books",
  bookDetail: "/books/:id",
  bookProgress: "/books/:id/progress",
  bookPageAssets: "/assets/book-pages/:id/*",
  bookChapterCoverAsset: "/assets/book-chapters/:id/cover",
  bookCoverAsset: "/assets/books/:id/cover",
  studios: "/studios",
  performers: "/performers",
  performerDetail: "/performers/:id",
  performerAssets: "/assets/performers/:id/*",
  scraperScrapePerformer: "/scrapers/:id/scrape-performer",
  tags: "/tags",
  scrapers: "/scrapers",
  scraperPackages: "/scrapers/packages",
  scraperPackageDetail: "/scrapers/packages/:id",
  scrapersIndex: "/scrapers/index",
  scraperScrape: "/scrapers/:id/scrape",
  scrapeResults: "/scrapers/results",
  scrapeResultDetail: "/scrapers/results/:id",
  scrapeResultAccept: "/scrapers/results/:id/accept",
  scrapeResultReject: "/scrapers/results/:id/reject",
  // Stash-Box endpoints
  stashBoxEndpoints: "/stashbox-endpoints",
  stashBoxEndpointDetail: "/stashbox-endpoints/:id",
  stashBoxEndpointTest: "/stashbox-endpoints/:id/test",
  stashBoxIdentify: "/stashbox-endpoints/:id/identify",
  stashBoxIdentifyPerformer: "/stashbox-endpoints/:id/identify-performer",
  stashBoxLookupStudio: "/stashbox-endpoints/:id/lookup/studio",
  stashBoxLookupTag: "/stashbox-endpoints/:id/lookup/tag",
  clientInfo: "/client-info",
  stashBoxLookupPerformer: "/stashbox-endpoints/:id/lookup/performer",
  // Unified metadata providers
  metadataProviders: "/metadata-providers",
  search: "/search",
  // Audio
  audioLibraries: "/audio-libraries",
  audioLibraryDetail: "/audio-libraries/:id",
  audioLibraryStats: "/audio-libraries/stats",
  audioLibraryCover: "/audio-libraries/:id/cover",
  audioLibraryIcon: "/audio-libraries/:id/icon",
  audioLibraryTrackUpload: "/audio-libraries/:id/tracks/upload",
  audioTracks: "/audio-tracks",
  audioTrackDetail: "/audio-tracks/:id",
  audioTrackMarkers: "/audio-tracks/:id/markers",
  audioTrackMarkerDetail: "/audio-tracks/markers/:id",
  audioStream: "/audio-stream/:id",
  audioTrackWaveform: "/assets/audio-tracks/:id/waveform",
  audioLibraryCoverAsset: "/assets/audio-libraries/:id/cover",
  audioLibraryIconAsset: "/assets/audio-libraries/:id/icon",
  // Collections
  collections: "/collections",
  collectionDetail: "/collections/:id",
  collectionItems: "/collections/:id/items",
  collectionItemDetail: "/collections/:id/items/:itemId",
  collectionItemsReorder: "/collections/:id/items/reorder",
  collectionRefresh: "/collections/:id/refresh",
  collectionPreviewRules: "/collections/preview-rules",
  collectionCover: "/collections/:id/cover",
  collectionCoverAsset: "/assets/collections/:id/cover",
  playlistSession: "/playlist-session",
  // Plugins
  pluginPackages: "/plugins/packages",
  pluginPackageDetail: "/plugins/packages/:id",
  pluginPackageAuth: "/plugins/packages/:id/auth",
  pluginPackageAuthKey: "/plugins/packages/:id/auth/:key",
  pluginsIndex: "/plugins/index",
  pluginExecute: "/plugins/:id/execute",
  pluginBatch: "/plugins/batch",
  pluginBatchStatus: "/plugins/batch/:jobId",
  pluginFolderCascade: "/plugins/:id/folder-cascade",

  // Video accept (scrape-accept)
  videoMovieAcceptScrape: "/video/movies/:id/accept-scrape",
  videoEpisodeAcceptScrape: "/video/episodes/:id/accept-scrape",
  videoSeriesAcceptScrape: "/video/series/:id/accept-scrape",

  // Typed video library (cascade-accept flow)
  videoLibraryCounts: "/video/library/counts",
  videoMovies: "/video/movies",
  videoMovieDetail: "/video/movies/:id",
  videoLibrarySeries: "/video/series",
  videoLibrarySeriesDetail: "/video/series/:id",
  videoEpisodeDetail: "/video/episodes/:id",

  // Unified /videos route (backed by video_episodes + video_movies)
  videos: "/videos",
  videoDetail: "/videos/:id",
  videoStats: "/videos/stats",
  videoResetMetadata: "/videos/:id/reset-metadata",
  videoSubtitles: "/videos/:id/subtitles",
  videoSubtitleDetail: "/videos/:id/subtitles/:trackId",
  videoSubtitleSource: "/videos/:id/subtitles/:trackId/source",
  videoSubtitleCues: "/videos/:id/subtitles/:trackId/cues",
  videoSubtitleExtract: "/videos/:id/subtitles/extract",
  videoAssets: "/assets/videos/:id/*",
  videoScrape: "/videos/:id/scrape",

  // Series (UI browser; typed endpoints above live under /video/series for
  // the cascade/accept flow and return a different shape)
  videoSeries: "/video-series",
  videoSeriesDetail: "/video-series/:id",
  videoSeriesCover: "/video-series/:id/cover",
  videoSeriesBackdrop: "/video-series/:id/backdrop",
  videoSeriesCoverAsset: "/assets/video-series/:id/cover",
  videoSeriesBackdropAsset: "/assets/video-series/:id/backdrop",

  videoStream: "/video-stream/:id",
  videoStreamSource: "/video-stream/:id/source",
  videoStreamHlsStatus: "/video-stream/:id/hls/status",
  videoStreamHlsMaster: "/video-stream/:id/hls/master.m3u8",
  videoStreamHlsFile: "/video-stream/:id/hls/*",

  // System
  systemStatus: "/system/status",
  systemBreakingGateAccept: "/system/breaking-gate/accept",
} as const;
