/** Tag name → chip class for gallery / dashboard cards (shared with video grid). */
export const VIDEO_TAG_COLORS: Record<string, string> = {
  Outdoor: "tag-chip-success",
  Indoor: "tag-chip-default",
  Interview: "tag-chip-info",
  BTS: "tag-chip-warning",
  Solo: "tag-chip-accent",
  Group: "tag-chip-error",
  POV: "tag-chip-info",
  Cinematic: "tag-chip-accent",
  Ambient: "tag-chip-success",
  Documentary: "tag-chip-info",
  "Studio Lit": "tag-chip-warning",
  "Natural Light": "tag-chip-success",
  Handheld: "tag-chip-default",
  Steadicam: "tag-chip-accent",
  Drone: "tag-chip-info",
  "Slow Motion": "tag-chip-warning",
  "Time Lapse": "tag-chip-success",
  Bondage: "tag-chip-error",
  Toys: "tag-chip-warning",
  Massage: "tag-chip-success",
  Cosplay: "tag-chip-accent",
  Vintage: "tag-chip-warning",
  Anal: "tag-chip-error",
  Oral: "tag-chip-info",
};
