import type { Component } from "svelte";
import {
  Activity,
  Building2,
  BookCopy,
  BookMarked,
  BookOpen,
  ChartNoAxesCombined,
  Clapperboard,
  Film,
  FolderOpen,
  FolderTree,
  Grid2x2,
  Image,
  Images,
  LayoutList,
  LayoutDashboard,
  MicVocal,
  Music,
  Palette,
  Puzzle,
  ScanSearch,
  Search,
  Send,
  Settings,
  Tags,
  Users,
  Wrench,
} from "@lucide/svelte";

/** Lucide components keyed by the `icon` slugs used in `appShellSections`. */
export const appShellNavIconMap: Record<string, Component<Record<string, unknown>>> = {
  "layout-dashboard": LayoutDashboard as unknown as Component<Record<string, unknown>>,
  film: Film as unknown as Component<Record<string, unknown>>,
  clapperboard: Clapperboard as unknown as Component<Record<string, unknown>>,
  images: Images as unknown as Component<Record<string, unknown>>,
  "book-open": BookOpen as unknown as Component<Record<string, unknown>>,
  "book-copy": BookCopy as unknown as Component<Record<string, unknown>>,
  "book-marked": BookMarked as unknown as Component<Record<string, unknown>>,
  image: Image as unknown as Component<Record<string, unknown>>,
  music: Music as unknown as Component<Record<string, unknown>>,
  "mic-vocal": MicVocal as unknown as Component<Record<string, unknown>>,
  users: Users as unknown as Component<Record<string, unknown>>,
  building: Building2 as unknown as Component<Record<string, unknown>>,
  tags: Tags as unknown as Component<Record<string, unknown>>,
  folder: FolderOpen as unknown as Component<Record<string, unknown>>,
  "folder-tree": FolderTree as unknown as Component<Record<string, unknown>>,
  "scan-search": ScanSearch as unknown as Component<Record<string, unknown>>,
  send: Send as unknown as Component<Record<string, unknown>>,
  puzzle: Puzzle as unknown as Component<Record<string, unknown>>,
  activity: Activity as unknown as Component<Record<string, unknown>>,
  settings: Settings as unknown as Component<Record<string, unknown>>,
  search: Search as unknown as Component<Record<string, unknown>>,
  "chart-no-axes-combined": ChartNoAxesCombined as unknown as Component<Record<string, unknown>>,
  "grid-2x2": Grid2x2 as unknown as Component<Record<string, unknown>>,
  "layout-list": LayoutList as unknown as Component<Record<string, unknown>>,
  palette: Palette as unknown as Component<Record<string, unknown>>,
  wrench: Wrench as unknown as Component<Record<string, unknown>>,
};
